include:
  - board: corneish_zen_v2_left
    cmake-args: -DCONFIG_ZMK_WIDGET_LAYER_STATUS=n -DCONFIG_CUSTOM_WIDGET_LAYER_STATUS=n
  - board: corneish_zen_v2_right
    cmake-args: -DCONFIG_ZMK_WIDGET_LAYER_STATUS=n -DCONFIG_CUSTOM_WIDGET_LAYER_STATUS=n
