name: Custom ZMK Firmware Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:stable
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cache west modules
        uses: actions/cache@v3
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: West Init
        run: west init -l config
      
      - name: West Update
        run: west update
      
      - name: West Zephyr export
        run: west zephyr-export
      
      - name: West Build (Corneish Zen V2 Left)
        run: |
          west build -s zmk/app -b corneish_zen_v2_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_WIDGET_LAYER_STATUS=n -DCONFIG_CUSTOM_WIDGET_LAYER_STATUS=n
          cp build/zephyr/zmk.uf2 corneish_zen_v2_left_zmk.uf2
      
      - name: West Build (Corneish Zen V2 Right)
        run: |
          west build -s zmk/app -b corneish_zen_v2_right --pristine -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_WIDGET_LAYER_STATUS=n -DCONFIG_CUSTOM_WIDGET_LAYER_STATUS=n
          cp build/zephyr/zmk.uf2 corneish_zen_v2_right_zmk.uf2
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            corneish_zen_v2_left_zmk.uf2
            corneish_zen_v2_right_zmk.uf2 